
# install java 8

sudo add-apt-repository ppa:webupd8team/java
sudo apt update
sudo apt install oracle-java8-installer

sudo apt install oracle-java8-set-default

# install jenkins
cd /tmp && wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

echo 'deb https://pkg.jenkins.io/debian-stable binary/' | sudo tee -a /etc/apt/sources.list.d/jenkins.list

sudo apt update
sudo apt install jenkins

# install ansible

sudo apt-add-repository ppa:ansible/ansible

sudo apt update
sudo apt install ansible

